### ISSUE TITLE
TakeProfit?

### ISSUE THREAD

**Issue by aleph0ne** [AwolDes/goanda#5]
I know there's a StopLossOnFill and that works very well, but is there a TakeProfit option which allows me to set StopLossOnFill and TakeProfit when performing a Limit Order (the API at OANDA seems to support this).

I cannot find this in the code anywhere, even though the API and interface allow this.

**Comment by jSydorowicz21** [comment]
Hey there!

Thank you for your suggestion! I just took over the baton of maintaining this project and have included this feature in the next update to come out. I'll update this issue when that update rolls out

**Comment by jSydorowicz21** [comment]
This has been added in #14 which has been merged with main
